platform :ios, '9.0'

target 'August24' do
end

pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  'DevSupport',
]

pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'

pod 'FirebaseUI/Database', '~> 4.0'
pod 'FirebaseUI/Auth', '~> 4.0'
pod 'FirebaseUI/Phone', '~> 4.0'

pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end
